/* This file was autogenerated at {21:18:23} - do not edit it - any edits will be overwritten! */ 
package frc.robot;

import frc.utils.configfile.StormProp;

public final class Constants {
	public static final int LogitechControllerPort = StormProp.getInt("LogitechControllerPort",0);
	public static final int bumperThickness = StormProp.getInt("bumperThickness",0);
	public static final int drivetrainWheelbaseMeters = StormProp.getInt("drivetrainWheelbaseMeters",0);
	public static final String debugProperties = StormProp.getString("debugProperties","");
	public static final String robotName = StormProp.getString("robotName","");
	public static final int robotWidth = StormProp.getInt("robotWidth",0);
	public static final double StickNullSize = StormProp.getNumber("StickNullSize",0.0);
	public static final int robotLength = StormProp.getInt("robotLength",0);
	public static final String override = StormProp.getString("override","");
	public static final String navXConnection = StormProp.getString("navXConnection","");
	public static final int drivetrainTrackwidthMeters = StormProp.getInt("drivetrainTrackwidthMeters",0);

	public static final class Toggles {
		public static final boolean useDrive = StormProp.getBoolean("useDrive",false);
		public static final boolean useStormNet = StormProp.getBoolean("useStormNet",false);
		public static final boolean useNavX = StormProp.getBoolean("useNavX",false);
		public static final int udpListenerPort = StormProp.getInt("udpListenerPort",0);
		public static final boolean useStatusLights = StormProp.getBoolean("useStatusLights",false);
		public static final boolean useVision = StormProp.getBoolean("useVision",false);
	}

	public static final class SparkMax {
		public static final int Neo550CurrentLimit = StormProp.getInt("Neo550CurrentLimit",0);
		public static final int TemperatureRampThreshold = StormProp.getInt("TemperatureRampThreshold",0);
		public static final int FreeSpeedRPM = StormProp.getInt("FreeSpeedRPM",0);
		public static final int TemperatureRampLimit = StormProp.getInt("TemperatureRampLimit",0);
		public static final int Neo550FreeSpeedRPM = StormProp.getInt("Neo550FreeSpeedRPM",0);
		public static final int CurrentLimit = StormProp.getInt("CurrentLimit",0);
	}

	public static final class Drive {
		public static final int frontLeftEncoderID = StormProp.getInt("frontLeftEncoderID",0);
		public static final int turnki = StormProp.getInt("turnki",0);
		public static final int backRightSwivelID = StormProp.getInt("backRightSwivelID",0);
		public static final int frontRightDriveID = StormProp.getInt("frontRightDriveID",0);
		public static final int precisionSpeedScale = StormProp.getInt("precisionSpeedScale",0);
		public static final int driveSpeedScale = StormProp.getInt("driveSpeedScale",0);
		public static final int turnkd = StormProp.getInt("turnkd",0);
		public static final int frontLeftOffsetTicks = StormProp.getInt("frontLeftOffsetTicks",0);
		public static final int frontLeftDriveID = StormProp.getInt("frontLeftDriveID",0);
		public static final int frontLeftSwivelID = StormProp.getInt("frontLeftSwivelID",0);
		public static final String mk4iModuleKind = StormProp.getString("mk4iModuleKind","");
		public static final int backRightOffsetTicks = StormProp.getInt("backRightOffsetTicks",0);
		public static final int backLeftEncoderID = StormProp.getInt("backLeftEncoderID",0);
		public static final int backRightEncoderID = StormProp.getInt("backRightEncoderID",0);
		public static final int swivelEncoderTicksPerRotation = StormProp.getInt("swivelEncoderTicksPerRotation",0);
		public static final int driveYkp = StormProp.getInt("driveYkp",0);
		public static final int frontRightOffsetTicks = StormProp.getInt("frontRightOffsetTicks",0);
		public static final int backLeftSwivelID = StormProp.getInt("backLeftSwivelID",0);
		public static final int driveXkp = StormProp.getInt("driveXkp",0);
		public static final String driveType = StormProp.getString("driveType","");
		public static final int frontRightEncoderID = StormProp.getInt("frontRightEncoderID",0);
		public static final int backLeftOffsetTicks = StormProp.getInt("backLeftOffsetTicks",0);
		public static final int driveXkd = StormProp.getInt("driveXkd",0);
		public static final int frontRightSwivelID = StormProp.getInt("frontRightSwivelID",0);
		public static final int backRightDriveID = StormProp.getInt("backRightDriveID",0);
		public static final int driveXki = StormProp.getInt("driveXki",0);
		public static final int backLeftDriveID = StormProp.getInt("backLeftDriveID",0);
		public static final int turnkp = StormProp.getInt("turnkp",0);
		public static final int driveYki = StormProp.getInt("driveYki",0);
		public static final int driveYkd = StormProp.getInt("driveYkd",0);
	}

	public static final class OperatorConstants {
		public static final int kDriverControllerPort = StormProp.getInt("kDriverControllerPort",0);
	}
}

